### PR TITLE
A start with the Dutch language for i9300 TWRP

### PR DESCRIPTION
**Pull request by mfonville**
The translation is not yet complete, I might do so when I find more time. But at least all major actions are translated.

It is btw not tested, so I have no clue if it fits on the buttons and such.

### CODE REVIEW

**Comment by SdtBarbarossa** [comment]
are you still working on it or should i merge?

**Comment by mfonville** [comment]
You can merge it; the latter part I will do at a later moment and a second PR.
Is there btw any upstream TWRP for these translations too?

**Comment by SdtBarbarossa** [comment]
what do you mean with upstream twrp ?

**Comment by mfonville** [comment]
I mean that this theme and English texts do come from somewhere and are not i9300 specific, are they?

**Comment by SdtBarbarossa** [comment]
everything modified is in this tree.... nothing is made in device tree

**Comment by mfonville** [comment]
But where did the original GUI xml files come from, or did you make those yourself?

**Comment by SdtBarbarossa** [comment]
nope like i mentioned in the threads they are from z31s1g (the maker of material twrp theme) 

https://gerrit.omnirom.org/#/c/15382/

but i had to modify it for working with multilanguage

**Comment by mfonville** [comment]
ok, I understand.

Then I assume you will give him a PR at some point with your multi-language code and associated translations :-)

**Comment by SdtBarbarossa** [comment]
nope... if dees_troy and _that are ready with theier work i will completely rework this and then i send a git commit .... several features of this homebuilds will never be allowed in official builds (like lockscreen) so i cant do a pullrequest (also they only accept git commits to gerrit )

**Pull request merged**
